### ISSUE TITLE
ms-celeb pretrained model for weight initialization:

### ISSUE THREAD

**Issue by izhimahu** [amirhfarzaneh/dacl#3]
Hello, I can't find it download ms-celeb pretrained model for weight initialization.`No such file or directory: '/users/amirhf/models/resnet18_msceleb.pth'`

**Comment by amirhfarzaneh** [comment]
Hello,

I have added the msceleb pretrained model. You can see it on the main repo page now under the **Usage** section: https://github.com/amirhfarzaneh/dacl#usage

Thank you for your patience.
